version: '2'

networks:
  kafka-local:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafka-local
    ports:
      - "2181:2181"
  kafka:
    build: .
    networks:
      - kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
